#include "clf/ModelExceptions.hpp"

using namespace clf::exceptions;

ModelHasNotImplementedRHS::ModelHasNotImplementedRHS(Type const& type) : CLFException(), type(type) {
  message = "ERROR: clf::Model has not implemented the right hand side function";
  if( type==Type::VECTOR ) {
    message += ". Error generated by vector-valued implementation call";
  } else if( type==Type::COMPONENT ) {
    message += ". Error generated by component-wise implementation call";
  }
  message += " (clf::exceptions::ModelHasNotImplementedRHS).";
}
